---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################


# --- base website settings ---

title: Justin W. Wheeler
baseURL: https://jwf.io/
theme: toph
languageCode: en-us
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: false
googleAnalytics: G-7YT6EE93RQ


# --- security settings ---

security:
  exec:
    allow: ['^dart-sass-embedded$', '^git$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']


# --- markup settings ---

markup:
  asciidocExt:
    preserveTOC: true


# --- privacy settings ---

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  vimeo:
    enableDNT: true
  youtube:
    privacyEnhanced: true


# --- navigation menu ---

menu:
  nav:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: blog
      name: blog
      url: https://blog.jwf.io/
      weight: 20
    - identifier: open
      name: "#open"
      url: https://docs.fedoraproject.org/en-US/commops/
      weight: 30
    - identifier: legal
      name: legal
      url: /legal/
      weight: 40
  social:
    - identifier: gitlab
      name: GitLab
      url: https://gitlab.com/jwwheeler
      weight: 10
    - identifier: github
      name: GitHub
      url: https://github.com/jwflory
      weight: 20
    - identifier: mastodon
      name: Mastodon
      url: https://floss.social/@jwf
      weight: 30
    - identifier: x
      name: X
      url: https://x.com/jwf_foss
      weight: 40


# --- custom settings ---

params:
  biography:
    name: Justin W. Wheeler
    gender: Male
    email: contact@jww.sh
    blog: https://blog.jwf.io
    first_online: 2014
    knows_about: [
      "Ansible",
      "CentOS",
      "community management",
      "continuous integration (CI)",
      "CSS",
      "diversity",
      "Docker",
      "equity",
      "Fedora Project",
      "feminism",
      "Free Software",
      "gender",
      "git",
      "HTML",
      "inclusion",
      "jflory7",
      "jwf",
      "Linux",
      "open source",
      "Red Hat",
      "Red Hat Enterprise Linux (RHEL)",
      "RIT",
      "Rochester Institute of Technology",
      "RPM package management",
      "TeleIRC",
      "UNICEF",
      "user experience",
      "web development"
    ]
  colors:
    primary: darkorchid
    secondary: linen
    accent: darkslateblue
  description: Home of Justin W. Wheeler, an Open Source contributor and Free Software advocate from the United States.
  fonts:
    default: Open Sans
    default_weight: ":wght@500"
    title: Bungee Shade
    header: Roboto Slab
    header_weight: ":wght@500"
  images:
    - /img/logo.jpg
  git_repo: https://gitlab.com/jwwheeler/jwwheeler.gitlab.io
  hire_me: false
  social:
    github_username: jwflory
    gitlab_username: jwwheeler
    lastfm_username: jflory7
    linkedin_url: justinwflory
    x_username: jwf_foss


# --- internationalization settings ---

defaultContentLang: en
languages:
  ar:
    disabled: true
    languageDirection: rtl
    languageName: عربي
  en:
    languageName: English
  es:
    languageName: español
  hi:
    disabled: true
    languageName: हिन्दी
