---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################

# --- base website settings ---

title: Justin W. Flory
baseURL: https://jwf.io/
theme: toph
languageCode: en-us
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: false

googleAnalytics: G-7YT6EE93RQ

markup:
  asciidocExt:
    preserveTOC: true

# --- custom settings ---

params:
  biography:
    name: Justin W. Flory
    gender: Male
    email: contact@jwf.io
    blog: https://blog.jwf.io
    knows_about: >
      "Justin W. Flory",
      "jflory7",
      "jwf",
      "open source",
      "RIT",
      "Rochester Institute of Technology",
      "Fedora Project",
      "UNICEF"
  description: Home of Justin W. Flory, an Open Source contributor and Free Software advocate from the United States.
  git_repo: https://gitlab.com/jwflory/jwflory.gitlab.io
  # Are you looking for new opportunities? Set hire_me to "true" if you want your LinkedIn to show on the nav bar and
  # for boilerplate text on how to get in touch.
  hire_me: false
  paths:
    favicon: favicon.ico
    logo: img/logo.jpg
  social:
    github_username: jwflory
    gitlab_username: jwflory
    lastfm_username: jflory7
    linkedin_url: justinwflory
    twitter_username: jwf_foss
