---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################


# --- base website settings ---

title: Justin W. Flory
baseURL: https://jwf.io/
theme: toph
languageCode: en-us
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: false
googleAnalytics: G-7YT6EE93RQ


# --- markup settings ---

markup:
  asciidocExt:
    preserveTOC: true


# --- privacy settings ---

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  vimeo:
    enableDNT: true
  youtube:
    privacyEnhanced: true


# --- navigation menu ---

menu:
  nav:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: blog
      name: blog
      url: https://blog.jwf.io/
      weight: 20
    - identifier: open
      name: "#open"
      url: https://unicef.github.io/inventory/
      weight: 30
    - identifier: legal
      name: legal
      url: /legal/
      weight: 40
  social:
    - identifier: gitlab
      name: GitLab
      url: https://gitlab.com/jwflory
      weight: 10
    - identifier: github
      name: GitHub
      url: https://github.com/jwflory
      weight: 20
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/jwf_foss
      weight: 30


# --- custom settings ---

params:
  biography:
    name: Justin W. Flory
    gender: Male
    email: contact@jwf.io
    blog: https://blog.jwf.io
    first_online: 2014
    knows_about: [
      "Ansible",
      "CentOS",
      "community management",
      "continuous integration (CI)",
      "CSS",
      "diversity",
      "Docker",
      "equity",
      "Fedora Project",
      "feminism",
      "Free Software",
      "gender",
      "git",
      "HTML",
      "inclusion",
      "jflory7",
      "jwf",
      "Linux",
      "open source",
      "Red Hat",
      "Red Hat Enterprise Linux (RHEL)",
      "RIT",
      "Rochester Institute of Technology",
      "RPM package management",
      "TeleIRC",
      "UNICEF",
      "user experience",
      "web development"
    ]
  description: Home of Justin W. Flory, an Open Source contributor and Free Software advocate from the United States.
  images:
    - /img/logo.jpg
  git_repo: https://gitlab.com/jwflory/jwflory.gitlab.io
  # Are you looking for new opportunities? Set hire_me to "true" if you want your LinkedIn to show on the nav bar and
  # for boilerplate text on how to get in touch.
  hire_me: false
  paths:
    favicon: favicon.ico
  social:
    github_username: jwflory
    gitlab_username: jwflory
    lastfm_username: jflory7
    linkedin_url: justinwflory
    twitter_username: jwf_foss
