---
html_tidy:
  image: cimg/ruby:3.2
  stage: build

  needs: ["hugo_build"]

  before_script:
    - gem install htmlbeautifier
  script: htmlbeautifier --tab $(find public/ -name '*.html' -print)
  after_script: []

  artifacts:
    paths:
      - public
