---
hugo_build:
  image: cibuilds/hugo:0.143.1
  stage: build

  # Cache HTMLProofer data across builds
  cache:
    paths:
      - tmp/.htmlproofer
      - themes/toph/exampleSite/tmp/.htmlproofer

  script:
    # build main site
    - HUGO_ENV=production hugo
    - htmlproofer public/
        --allow-hash-href
        --no-ignore-missing-alt
        --enforce-https
        --ignore-status-codes 0,301,400,503
        --ignore-urls "/archive/v3/irc/,/spigotmc.org/,/linkedin.com/,/x.com/"

    # build example site
    - cd themes/toph/exampleSite
    - HUGO_ENV=production hugo --themesDir=../../
    - htmlproofer public/
        --allow-hash-href
        --no-ignore-missing-alt
        --enforce-https
        --ignore-status-codes 0,400,503,999
        --ignore-urls "/toph-hugo/,/x.com/"
  after_script: []

  artifacts:
    paths:
      - public
