---
image: ruby:latest

jekyll_build:
  # Cache gems in between builds
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - tmp/.htmlproofer
      - vendor/ruby

  before_script:
    - bundle config set path 'vendor/ruby'
    - gem install bundler
    - bundle install
  script: bundle exec rake test
  after_script:
    - mv _site/ public/

  artifacts:
    paths:
      - public
